apiVersion: apps/v1
kind: Deployment
metadata:
  name: opendkim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opendkim
  template:
    metadata:
      labels:
        app: opendkim
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - 'amd64'
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 15
            preference:
              matchExpressions:
              - key: core
                operator: In
                values:
                - '3'
          - weight: 10
            preference:
              matchExpressions:
              - key: core
                operator: In
                values:
                - '4'
      #hostNetwork: true
      # hostname: 'opendkim'
      imagePullSecrets:
      - name: ghcr.io
      # subdomain: opendkim
      containers:
      - name: opendkim
        image: ghcr.io/mcbtaguiad/mail-tagsdev/opendkim:v0.0.1-test
        imagePullPolicy: Always
        resources:
          limits:
            memory: 100Mi
            cpu: 25m
          requests:
            memory: 25Mi
            cpu: 10m
        ports:
        - name: opendkim
          containerPort: 8891
          protocol: TCP
          #hostPort: 8891
      restartPolicy: Always

