---
apiVersion: v1
kind: Service

metadata:
  name: mail
  labels:
    app: mail

spec:
  type: ClusterIP

  selector:
    app: mail

  ports:
    - name: transfer
      port: 25
      targetPort: 25
      protocol: TCP
    - name: esmtp-explicit
      port: 587
      targetPort: 587
      protocol: TCP
    - name: imap-implicit
      port: 993
      targetPort: 993
      protocol: TCP
    - name: pop3-implicit
      port: 143
      targetPort: 143
      protocol: TCP


