---
apiVersion: v1
kind: Service

metadata:
  name: mail
  labels:
    app: mail

spec:
  type: ClusterIP

  selector:
    app: mail

  ports:
    - name: smtp
      port: 25
      targetPort: 25
      protocol: TCP
    - name: smtps
      port: 465
      targetPort: 465
      protocol: TCP
    - name: submission
      port: 587
      targetPort: 587
      protocol: TCP
    - name: pop3s
      port: 995
      targetPort: 995
      protocol: TCP
    - name: imaps
      port: 993
      targetPort: 993
      protocol: TCP
    - name: imap
      port: 143
      targetPort: 143
      protocol: TCP


