apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mail-tls
  #namespace: mail
spec:
  secretName: mail-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  additionalOutputFormats:
  - type: CombinedPEM
  - type: DER
  #commonName: '*.tagsdev.xyz'
  dnsNames:
  - 'mail.tagsdev.xyz'
  #- 'tagsdev.xyz'
