apiVersion: apps/v1
kind: Deployment
metadata:
  name: spamassassin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spamassassin
  template:
    metadata:
      labels:
        app: spamassassin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - 'amd64'
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 15
            preference:
              matchExpressions:
              - key: core
                operator: In
                values:
                - '3'
          - weight: 10
            preference:
              matchExpressions:
              - key: core
                operator: In
                values:
                - '4'
      #hostNetwork: true
      # hostname: 'spamassassin'
      imagePullSecrets:
      - name: ghcr.io
      # subdomain: spamassassin
      containers:
      - name: spamassassin
        image: ghcr.io/mcbtaguiad/mail-tagsdev/spamassassin:v0.0.1-dev
        imagePullPolicy: Always
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 250m
        ports:
        - name: spamassassin
          containerPort: 783
          protocol: TCP
          #hostPort: 783
      restartPolicy: Always

