apiVersion: apps/v1
kind: Deployment
metadata:
  name: dovecot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dovecot
  template:
    metadata:
      labels:
        app: dovecot
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - 'amd64'
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 15
            preference:
              matchExpressions:
              - key: core
                operator: In
                values:
                - '4'
          - weight: 10
            preference:
              matchExpressions:
              - key: core
                operator: In
                values:
                - '3'
      # hostNetwork: true
      hostname: dovecot
      imagePullSecrets:
      - name: ghcr.io
      containers:
      - name: dovecot
        image: ghcr.io/mcbtaguiad/mail-tagsdev/dovecot:v0.0.1-test
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsUser: 0
          runAsGroup: 0
          runAsNonRoot: false
          privileged: false
          capabilities:
            add:
            # file permission capabilities
            - CHOWN
            - FOWNER
            - MKNOD
            - SETGID
            - SETUID
            - DAC_OVERRIDE
            # network capabilities
            - NET_ADMIN # needed for F2B
            - NET_RAW # needed for F2B
            - NET_BIND_SERVICE
            # miscellaneous  capabilities
            - SYS_CHROOT
            - KILL
            drop: [ALL]
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 250m

        volumeMounts:
        # - name: data
        #   mountPath: /var/mail/postfix/
        #   readOnly: false
        #   subPath: postfix

        - name: data
          mountPath: /var/mail/vhosts/tagsdev.xyz
          readOnly: false
          subPath: dovecot
        
        - name: mail-tls
          mountPath: /etc/mail/ssl/
          readOnly: true
          
        
        ports:
        - name: esmtp-explicit
          containerPort: 587
          protocol: TCP
          #hostPort: 587
        - name: imap-implicit
          containerPort: 993
          protocol: TCP
          #hostPort: 993
        - name: pop3-implicit
          containerPort: 143
          protocol: TCP
          #hostPort: 143
        - name: dovecot
          containerPort: 50001
          protocol: TCP
          #hostPort:50001

        # envFrom:
        # - configMapRef:
        #     name: dovecot.environment

      restartPolicy: Always
      #nodeSelector:
      #  kubernetes.io/hostname: luna

      initContainers:
      - name: volume-permission
        image: alpine:latest
        command:
          - sh
          - -c
          - 'chown -R 5000:5000 /var/mail/vhosts/tagsdev.xyz'
          - 'chmod -R 775 /var/mail/vhosts/tagsdev.xyz' 
        volumeMounts:
          - name: data
            mountPath: /var/mail/vhosts/tagsdev.xyz
        securityContext:
          runAsUser: 0

      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mail-pvc
      # certificates
      - name: mail-tls
        secret:
          secretName: mail-tls
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key




