---
apiVersion: v1
kind: Service

metadata:
  name: postfix
  labels:
    app: postfix

spec:
  type: ClusterIP

  selector:
    app: postfix

  ports:
    # Transfer
    - name: transfer
      port: 25
      targetPort: 25
      protocol: TCP
    # ESMTP with explicit TLS (STARTTLS)
    - name: smtp-587
      port: 587
      targetPort: 587
      protocol: TCP
    - name: smtp-465
      port: 465
      targetPort: 465
      protocol: TCP


