---
apiVersion: v1
kind: Service

metadata:
  name: dovecot
  labels:
    app: dovecot

spec:
  type: ClusterIP

  selector:
    app: dovecot

  ports:
    # IMAPS with implicit TLS
    - name: imap-implicit
      port: 993
      targetPort: 993
      protocol: TCP
    - name: pop3-implicit
      port: 995
      targetPort: 995
      protocol: TCP


