---
apiVersion: v1
kind: Service

metadata:
  name: opendkim
  labels:
    app: opendkim
spec:
  type: ClusterIP
  selector:
    app: opendkim
  ports:
    - name: opendkim
      port: 8891
      targetPort: 8891
      protocol: TCP


