---
apiVersion: v1
kind: Service

metadata:
  name: spamassassin
  labels:
    app: spamassassin
spec:
  type: ClusterIP
  selector:
    app: spamassassin
  ports:
    - name: spamassassin
      port: 783
      targetPort: 783
      protocol: TCP


